//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 4.0.30319.42000
//
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoNai3Tools.Properties
{


    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoNai3Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string AppTitle
        {
            get
            {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        internal static string AppVersionUnknown
        {
            get
            {
                return ResourceManager.GetString("AppVersionUnknown", resourceCulture);
            }
        }

        internal static string Button_Generate
        {
            get
            {
                return ResourceManager.GetString("Button_Generate", resourceCulture);
            }
        }

        internal static string Button_Run
        {
            get
            {
                return ResourceManager.GetString("Button_Run", resourceCulture);
            }
        }

        internal static string Button_Running
        {
            get
            {
                return ResourceManager.GetString("Button_Running", resourceCulture);
            }
        }

        internal static string Button_Stop
        {
            get
            {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }

        internal static string Dialog_SelectDefaultFileName
        {
            get
            {
                return ResourceManager.GetString("Dialog_SelectDefaultFileName", resourceCulture);
            }
        }

        internal static string Dialog_SelectTitle
        {
            get
            {
                return ResourceManager.GetString("Dialog_SelectTitle", resourceCulture);
            }
        }

        internal static string GroupBox_FixedArtist
        {
            get
            {
                return ResourceManager.GetString("GroupBox_FixedArtist", resourceCulture);
            }
        }

        internal static string GroupBox_RandomArtist
        {
            get
            {
                return ResourceManager.GetString("GroupBox_RandomArtist", resourceCulture);
            }
        }

        internal static string Hover_InsertRemoveFixedArtist
        {
            get
            {
                return ResourceManager.GetString("Hover_InsertRemoveFixedArtist", resourceCulture);
            }
        }

        internal static string Hover_InsertRemoveRandomArtist
        {
            get
            {
                return ResourceManager.GetString("Hover_InsertRemoveRandomArtist", resourceCulture);
            }
        }

        internal static string Msg_AddSnippetFailed
        {
            get
            {
                return ResourceManager.GetString("Msg_AddSnippetFailed", resourceCulture);
            }
        }

        internal static string Msg_ConfigNameEmpty
        {
            get
            {
                return ResourceManager.GetString("Msg_ConfigNameEmpty", resourceCulture);
            }
        }

        internal static string Msg_DeleteConfigFailed
        {
            get
            {
                return ResourceManager.GetString("Msg_DeleteConfigFailed", resourceCulture);
            }
        }

        internal static string Msg_DeleteSnippetFailed
        {
            get
            {
                return ResourceManager.GetString("Msg_DeleteSnippetFailed", resourceCulture);
            }
        }

        internal static string Msg_DirectorToolFailed
        {
            get
            {
                return ResourceManager.GetString("Msg_DirectorToolFailed", resourceCulture);
            }
        }

        internal static string Msg_InvalidGenerationParams
        {
            get
            {
                return ResourceManager.GetString("Msg_InvalidGenerationParams", resourceCulture);
            }
        }

        internal static string Msg_LanguageRestartPrompt
        {
            get
            {
                return ResourceManager.GetString("Msg_LanguageRestartPrompt", resourceCulture);
            }
        }

        internal static string Msg_NoImagesInFolder
        {
            get
            {
                return ResourceManager.GetString("Msg_NoImagesInFolder", resourceCulture);
            }
        }

        internal static string Msg_ReadConfigFailed
        {
            get
            {
                return ResourceManager.GetString("Msg_ReadConfigFailed", resourceCulture);
            }
        }

        internal static string Msg_SaveConfigFailed
        {
            get
            {
                return ResourceManager.GetString("Msg_SaveConfigFailed", resourceCulture);
            }
        }

        internal static string Msg_SelectConfigToDelete
        {
            get
            {
                return ResourceManager.GetString("Msg_SelectConfigToDelete", resourceCulture);
            }
        }

        internal static string Msg_SelectImageFirst
        {
            get
            {
                return ResourceManager.GetString("Msg_SelectImageFirst", resourceCulture);
            }
        }

        internal static string Msg_SelectValidInputFolder
        {
            get
            {
                return ResourceManager.GetString("Msg_SelectValidInputFolder", resourceCulture);
            }
        }

        internal static string Msg_UpdateSnippetFailed
        {
            get
            {
                return ResourceManager.GetString("Msg_UpdateSnippetFailed", resourceCulture);
            }
        }

        internal static string Msg_WildcardFolderNotConfigured
        {
            get
            {
                return ResourceManager.GetString("Msg_WildcardFolderNotConfigured", resourceCulture);
            }
        }

        internal static string Title_Error
        {
            get
            {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }

        internal static string Title_Info
        {
            get
            {
                return ResourceManager.GetString("Title_Info", resourceCulture);
            }
        }

        internal static string Title_Prompt
        {
            get
            {
                return ResourceManager.GetString("Title_Prompt", resourceCulture);
            }
        }
    }
}
